backend:
  name: git-gateway
  branch: main
media_folder: 'public/img'
public_folder: img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Artist Name", name: "artist_name", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "songs"
    label: "Songs"
    description: "Add your repertoire here along with chords, lyrics and other information."
    folder: 'content/songs'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Name', name: 'name', widget: 'string'}
      - {label: 'Chords', name: 'chords', widget: 'markdown', buttons: ['bold', 'italic', 'heading-one', 'heading-two'], editor_components: []}
      - {label: 'Lyrics', name: 'lyrics', widget: 'markdown'}
      - {label: 'Key', name: 'key', widget: 'string'}
      - {label: 'Time Signature', name: 'time_signature', widget: 'string'}
      - {label: 'Tempo', name: 'tempo', widget: 'number', default: 120, value_type: "int", min: 0, max: 1000}
      - {label: 'Video Link', name: 'video_link', widget: 'string'}
      - {label: 'Audio Link', name: 'audio_link', widget: 'string'}
